### ISSUE TITLE
Absolute path support

### ISSUE THREAD

**Issue by LeonBaudouin** [UstymUkhman/vite-plugin-glsl#21]
Hi !

In my projects, I organise my glsl code by components like so:

```
root
├── src/
│   ├── utils/
│   │   └── glsl/
│   │       ├── chunk1.glsl
│   │       └── chunk2.frag
│   ├── components/
│   │   └── Cube/
│   │       ├── index.js
│   │       └── index.frag
│   │       └── index.vert
│   └── main.js
├── vite.config.js
└── package.json
```

It seems that the loader doesn't support absolute import paths, which makes it really tedious for me to use. I don't really want to change my way of coding because of a tool that should help me. Do you plan to add this feature?

```glsl
// index.frag
precision highp float;

#include /utils/glsl/chunk1.glsl;

out highp vec4 fragColor;

void main (void) {
  fragColor = chunkFn();
}
```

As far as I know, there is no such feature in any glsl loader.

**Comment by UstymUkhman** [comment]
Hi @LeonBaudouin, thanks for opening this issues. I agree, this seems a useful enhancement indeed. I made a quick test and it seems to be pretty straight forward to implement except for one thing: since `vite.config` is running in the project root directory, I cannot guarantee the `src` folder to be the root of all shader files (vite does not force you to use it or even call it exactly like that), so based on your example, the absolute import within the shader file should look like this:

`#include /src/utils/glsl/chunk1.glsl;`

And there's also an improvement that can be done here: I can add an option to change the default root directory (`'/'`) to whatever fits the most your project structure. Example:

```js
// vite.config.js
import glsl from 'vite-plugin-glsl';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [glsl({ root: 'src/' })]
});
```

so you can import your shaders starting from the '/src' directory. Or even `plugins: [glsl({ root: 'src/shaders/' })]` that will be a preferred option for those who like to keep all shaders in one folder, like me. I've made an initial update [here](https://github.com/UstymUkhman/vite-plugin-glsl/commit/f63c440a3ffd085b4f179244678ef035edc620d9) and it seem to be already working but I want to test this a bit more and add the configuration option I mentioned above. I will close this issue once the new version will be available on NPM. Please let me know if that would work for you and please consider ⭐ing this plugin. Thanks!

**Comment by LeonBaudouin** [comment]
Hey @UstymUkhman ! It's surprising that the solution is so straightforward. An option to change the root of the shader folder would be ideal for me ! The `src` folder was just an example, I'm currently using this plugin with Nuxt3 so the project structure is quite different.
Thx for digging into that so quickly. I can't wait to fully benefit of this plugin !

**Comment by UstymUkhman** [comment]
Closing this since `v0.4.0` was just released with support for absolute path imports & `root` option to override the default project root directory for shader chunks. Thanks!

**Comment by dghez** [comment]
this is gold. thanks sir.
