### ISSUE TITLE
Import other NPM packages i.e. glsl-noise

### ISSUE THREAD

**Issue by brunoimbrizi** [UstymUkhman/vite-plugin-glsl#28]
With [glslify](https://github.com/glslify/glslify) we can import files from the same code base and also from other NPM packages. i.e. [glsl-noise](https://github.com/hughsk/glsl-noise) or [glsl-blend](https://github.com/jamieowen/glsl-blend)

With vite-plugin-glsl, what would be the equivalent to the following?
```
// my-shader.glsl
#pragma glslify: snoise3 = require(glsl-noise/simplex/3d)
```

**Comment by UstymUkhman** [comment]
Hi @brunoimbrizi , thanks for using `vite-plugin-glsl` and opening an issue here. I'm afraid I haven't completely understood you question thought.

If your asking if that's possible to import and use just one function from a `glsl` file like `glslify` can do, then the answer is no, and it is by design. You can import just whole chunks, but you can also use `#ifdef`, `#ifndef` and `#define` macros to create some logic around which file you actually need to use. Feel free to check [this comment](https://github.com/UstymUkhman/vite-plugin-glsl/issues/10#issuecomment-1166647716) for some examples.

If you're asking how to import `glsl` files from some NPM package, then the way to go is to use `optimizeDeps` in your `vite.config`. These are some issues that might help you with that:

- https://github.com/UstymUkhman/vite-plugin-glsl/issues/18
- https://github.com/UstymUkhman/vite-plugin-glsl/issues/20

Feel free to add some more info if your goal is to achieve a different behavior. Thanks!

**Comment by brunoimbrizi** [comment]
Hi @UstymUkhman, thank you for the detailed answer. I tried to keep the question short, but maybe it was too short, let me clarify it further. The intent was to understand if there is a way to achieve the same convenience as when using glslify. 

Taking [glsl-noise](https://www.npmjs.com/package/glsl-noise) as an example (a popular package with 137K weekly downloads), it's quite convenient to install it with NPM and import it from a GLSL file as such:
```
#pragma glslify: snoise2 = require(glsl-noise/simplex/2d) 
#pragma glslify: snoise3 = require(glsl-noise/simplex/3d)
```
It's also convenient to import the modules as a functions, in case two different noises are needed in the same file.

Now I'm working on a project with `vite` and I need to import `glsl-noise` into a few of the shaders. I managed to do it with `vite-plugin-glsl`, but the process was very hacky and inelegant, so I'm reaching out to see if there's a better way of doing it. Here's what I did:

1. I couldn't find a way to reference the package by name, so I had to use a relative path
i.e. `#include ../../../node_modules/glsl-noise/simplex/3d`
2. That includes the file, but a shader error is thrown because the file contains a [#pragma glslify](https://github.com/hughsk/glsl-noise/blob/master/simplex/3d.glsl#L104) statementI had to edit the file and remove the statement, so I copied folder `/simplex` from `node_modules` into my project source and updated the `#include` accordingly — losing the modularity provided by NPM
4. This worked for shaders which required only one of the noise functions, but failed for those which required both 2D and 3D noises (`snoise2` and `snoise3`) because both include functions with the same names i.e. [vec3 mod289](https://github.com/hughsk/glsl-noise/blob/master/simplex/3d.glsl#L12)

**Comment by brunoimbrizi** [comment]
Hi @UstymUkhman, thank you for the detailed answer. I tried to keep the question short, but maybe it was too short, let me clarify it further. The intent was to understand if there is a way to achieve the same convenience as when using `glslify`. 

Taking [glsl-noise](https://www.npmjs.com/package/glsl-noise) as an example, it's quite convenient to install it with NPM and import it from a GLSL file as such:
```
#pragma glslify: snoise2 = require(glsl-noise/simplex/2d) 
#pragma glslify: snoise3 = require(glsl-noise/simplex/3d)
```
It's also convenient to import the modules as a functions, in case multiple noises are needed in the same file.

Now I'm working on a project with `vite` and I need to import `glsl-noise` into a few of the shaders. I managed to do it with `vite-plugin-glsl`, but the process was quite hacky and inelegant, so I'm reaching out to see if there's a better way to do it. Here's what I did:

1. I didn't know how to reference the package by name, so I used a relative path
i.e. `#include ../../../node_modules/glsl-noise/simplex/3d`
2. That included the contents of the file as expected, but a shader error was thrown because it contains a [#pragma glslify](https://github.com/hughsk/glsl-noise/blob/master/simplex/3d.glsl#L104) statement. I had to edit the file and remove the statement, so I copied folder `/simplex` from `node_modules` into my project and updated the `#include` accordingly.
3. That worked for shaders which required only one of the noise functions, but failed for those which required both 2D and 3D noises (`snoise2` and `snoise3`) because both include functions with the same names i.e. [vec3 mod289](https://github.com/hughsk/glsl-noise/blob/master/simplex/3d.glsl#L12). I had to edit the files further and rename the conflicting functions, appending arbitrary suffixes to their names.

The above hacks worked, but the modularity provided by NPM was lost and the original files were butchered.

I understand `glsl-noise` was written with `glslify` in mind, but given its popularity (137K weekly downloads) and the rising adoption of `vite` I assume I'm not the first one to need to use them together. `vite-plugin-glsl` seems to be the _de facto_ standard for using GLSL with vite, but I couldn't find an example of how to use it in the scenario above.

**Comment by UstymUkhman** [comment]
Ok, I got your point, thanks for a detailed explanation on what you're trying to do. The show answer is: as mentioned [here](https://github.com/UstymUkhman/vite-plugin-glsl/issues/4), it's not possible to use `glslify` modules with this plugin. 🙂

And now the long answer. `glslify` leverages to import and export shader functions by defining a custom `#pragma glslify` directive. All their stack.gl ecosystem is built around this non-standard approach. As far as I know, the `#include` directive is also non-standard in WebGL, but it is in **C**, **HLSL** and seems to be used a lot anyways in projects like *three.js*, *lygia*, many existing shader loaders for webpack and so on... Also it's way more intuitive to understand what is doing a line that starts with an `#include` statement. That's why I picked it over some other syntax.

Basically, you have two options: continue using `glslify` with some other bundler if it doesn't support vite or focus on some alternatives to the `glslify` ecosystem. Lygia for example, has a lot of noise functions in [here](https://github.com/patriciogonzalezvivo/lygia/tree/main/generative) and many more utilities or take a look at [webgl-noise](https://github.com/stegu/webgl-noise) from Stefan Gustavson (I'm pretty sure glslify is based on his work).

Then you can also use the `root` option if you're going to install all your shaders in one directory to keep include paths as simple as possible. As for the last point you mentioned (both included functions have the same name), yeah, the `vec3 mod289` in `/simplex/3d` is exactly the same function that in `/simplex/2d` and since `vite-plugin-glsl` does not create any scope  for variables or functions defined within one chuck, one of those needs to be removed. The best approach I can think of is to move those util functions like `mod289` to one `.glsl` file and include that at the beginning. In this way you'll end up with a shorter output shader file 'cause further noise functions will be using the already defined utils functions. 😉
