### ISSUE TITLE
can't 'go to definition' to source file

### ISSUE THREAD

**Issue by lslzl3000** [UstymUkhman/vite-plugin-glsl#36]
I know this is working for `ts` by define custom module in `ext.d.ts`
but if try to 'go to definition' for those modules, it can only redirect to the `ext.d.ts`, not the source file

Any idea how to redirect to the source file?

**Comment by UstymUkhman** [comment]
Nope. If you'll find a way, please let me know here. 🙂

**Comment by UstymUkhman** [comment]
@lslzl3000 Can you please check if changing this

```
"exports": {
    ".": "./src/index.js",
    "./ext": {
      "types": "./ext.d.ts"
    }
  },
```

to this

```
"exports": {
    ".": {
      "module": "./src/index.js",
      "types": "./src/index.d.ts"
    },
    "./ext": {
      "types": "./ext.d.ts"
    }
  },
```

in `package.json` will fix your issue? Thanks a lot!

**Comment by lslzl3000** [comment]
> @lslzl3000 Can you please check if changing this
> 
> ```
> "exports": {
>     ".": "./src/index.js",
>     "./ext": {
>       "types": "./ext.d.ts"
>     }
>   },
> ```
> 
> to this
> 
> ```
> "exports": {
>     ".": {
>       "module": "./src/index.js",
>       "types": "./src/index.d.ts"
>     },
>     "./ext": {
>       "types": "./ext.d.ts"
>     }
>   },
> ```
> 
> in `package.json` will fix your issue? Thanks a lot!


it seems change nothing, still redirect to the `ext.d.ts`

I checked the `ts` plugin source, look like there is a way to custom 'go to definition':
https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

![Screenshot 2023-03-12 at 17 26 06](https://user-images.githubusercontent.com/3398981/224535996-4f8fd5d7-05d2-4708-b7aa-b3201c0bb194.png)

but I can't find any demos

**Comment by UstymUkhman** [comment]
Thanks for your help @lslzl3000 , I'll check it!

**Comment by UstymUkhman** [comment]
Hi again @lslzl3000! Sorry, but I feel like I've losts the point of your expected result here. If I "Go to definition" from the plugin import in `vite.config`, it redirects me to the type definition of `glsl` function and that allows me to check the type of config object it's expecting to receive (desired behavior). If I "Go to definition" of shaders' type reference, as you said, it redirects me to the `ext.d.ts` file in order to check supported shaders extensions (again, as expected).

Are you trying to reach JavaScript code from one of those definitions? For what reason? I would argue that the implementation should remain hidden and plugin should expose just the API definitions in order for a developer to know how to use it. Sorry if I've missed your point, could you elaborate a bit more? Thanks!

[vite-plugin-glsl.webm](https://user-images.githubusercontent.com/9247261/224926201-2dee1c97-92ea-4702-9abe-56b0182e77d3.webm)

**Comment by lslzl3000** [comment]
My point was not go to the source code of this plugin, I am try to redirect to the source of a `glsl/string/..` file import from the plugin.

```ts
import shader from '/path/to/some.glsl'
```
`ts` by default cannot 'go to definition' of  the `shader` var, I want to quick redirect to `/path/to/some.glsl`

https://user-images.githubusercontent.com/3398981/224931588-d5c9f03f-ab54-4df1-9895-64eef3dfb6ea.mov

**Comment by UstymUkhman** [comment]
Oh, got it, thanks! I will investigate this further.

**Comment by UstymUkhman** [comment]
Hey @lslzl3000! I've checked how these "Go To Definition" are working and how to implement a custom behavior, but it seems to me like it's required to create a custom Extension or "Language Service Plugin" in order to customize this functionality for `glsl` files within VS Code.

Unfortunately, this is beyond the scope of this plugin, but if I'm wrong here and this feature can be implemented fairly easily in the current code base, please feel free to submit a PR. Here's some more info I've found about custom "Go To Definition"s that might be usefull:

- https://github.com/microsoft/vscode-cpptools/issues/1157
- https://stackoverflow.com/questions/69819469/in-vs-code-how-can-i-make-a-custom-go-to-definition-functionality-for-a-non-s
