### ISSUE TITLE
Compress erros on Three with chunks and imports

### ISSUE THREAD

**Issue by dghez** [UstymUkhman/vite-plugin-glsl#48]
First of all, great plugin, thanks for that.
I tried to use the `compress: true` prop to compress my shader but somehow it breaks the code.
My files includes both `import` and a lot of `threejs chuks` (aka <#include... >)

Any clue?
I'm on `"vite-plugin-glsl": "^1.1.2"` and `"three": "^0.157.0"`

**EDIT:** in the docs you stated _"Starting from v0.5.4 this plugin supports custom compress callback function to optimize output shader length after all shader chunks have been included."_ so it might solve my issue but I have no clue on what I need to do there since docs are not explain that :)

<img width="924" alt="image" src="https://github.com/UstymUkhman/vite-plugin-glsl/assets/6367879/3fe08387-c234-4efe-9174-c85ce4e56d00">

**Comment by dghez** [comment]
Hey there, thanks for the reply!
I think I found the issue, it wasn't a typo but more like a "compress issue"
```
    return
        g0( fuv.y ) * ( g0x * textureLod( tex, p0, lod ) + g1x * textureLod( tex, p1, lod ) )
        + g1( fuv.y ) * ( g0x * textureLod( tex, p2, lod ) + g1x * textureLod( tex, p3, lod ) );
 ```
 
 These lines were the issue and it was because there were a "enter2 (break row) after the return that was messing with everything, I removed that and I got no issues.

But honestly I can just see a whitespace saving, removing spaces between parentheses, not much more.
Is there a way to trigger a sort of minimize/uglify? Renaming variables, compress etc.. you know, classic js thing

**Comment by UstymUkhman** [comment]
Hahahaha... I guess that might also happen in JavaScript. 😅

> But honestly I can just see a whitespace saving, removing spaces between parentheses, not much more.
Is there a way to trigger a sort of minimize/uglify? Renaming variables, compress etc.. you know, classic js thing

Kinda... As you mentioned, this plugin supports custom `compress` callback function, so what you can do is to use that:

```
glsl({
  compress: (outputShader) => customUglifier(outputShader),
})
```

where `customUglifier` is a function that takes in input your shader code (already parsed, with chunks included) and can minimize/uglify it as you wish. It then has to return the minified version of it.

What default `compress` algorithm is aimed to do at the end of the day, is to strip away whitespaces from your shaders in order to reduce bundle size and load them a bit faster. That's it. It is by design 'cause in 99% of cases this should be enough, but with custom `compress` function you have an API to cover the other 1% of cases like uglifing, etc... 😉

P.S.: Thanks you your star on this project. ❤️
